import LocalizedStrings from 'react-native-localization';

const Lang = new LocalizedStrings({
    en:{
        password:"Password",
        password_confirmation: "Confirm password",
        login:"Login",
        submit:"Submit",
        register: "Register",
        name: "Name",
        confirmPolicy: 'I agree to the terms of service',
        resetPassword: 'Password Reset',
        diary: 'Diary',
        trainers: 'Trainers',
        food: 'Food',
        activity: 'Activity',
        progress: 'Progress',
        personal: 'Personal',
        diary_food: 'Food Diary',
        diary_activity: 'Activity Diary',
        selectedDate: 'Selected date:',
        foodName: 'Product Name',
        date: 'Date',
        time: 'Time',
        kcal: 'Kcal',
        weightPortion: 'Portion Weight',
        close: 'Close',
        save: 'Save',
        protein: 'Protein (g)',
        fat: 'Fat (g)',
        carbohydrates: 'Carbohydrate (g)',
        water: 'Water (g)',
        activityName: 'Activity name',
        numberApproaches: 'Number of approaches*',
        timeOneExercise: 'Time to complete the approach*',
        numberOfRepetitions: 'Number of repetitions',
        restNextToApproach: 'Rest time to next approach',
        burdenWeight: 'Burden weight',
        searchNickName: 'Search by nickname',
        allTrainers: 'All trainers',
        myTrainers: 'My trainers',
        subscribe: 'Subscribe',
        unsubscribe: 'Unsubscribe',

    },
    de: {
        password:"Passwort",
        password_confirmation: "Passwort bestätigen",
        login:"Anmeldung",
        submit:"Einreichen",
        register: "Anmelden",
        name: "Name",
        confirmPolicy: 'Ich stimme den Nutzungsbedingungen zu',
        resetPassword: 'Passwort zurücksetzen',
        diary: 'Tagebuch',
        trainers: "Trainer",
        food: 'Essen',
        activity: 'Aktivität',
        progress: 'Fortschritt',
        personal: 'Persönlich',
        diary_food: 'Ernährungstagebuch',
        diary_activity: 'Aktivitätstagebuch',
        selectedDate: 'Ausgewähltes Datum:',
        foodName: 'Produktname',
        date: 'Datum',
        time: 'Zeit',
        kcal: 'Kcal',
        weightPortion: 'Portionsgewicht',
        close: 'Schließen',
        save: 'Speichern',
        protein: "Proteine (g)",
        fat: "Fett (g)",
        carbohydrates: "Kohlenhydrate (g)",
        water: "Wasser (g)",
        activityName: 'Aktivitätsname',
        numberApproaches: 'Anzahl Ansätze*',
        timeOneExercise: 'Zeit für den Abschluss des Ansatzes*',
        numberOfRepetitions: 'Anzahl der Wiederholungen',
        restNextToApproach: 'Ruhezeit bis zum nächsten ansatz',
        burdenWeight: 'Belasten Sie Gewicht',
        searchNickName: 'Suche nach Spitznamen',
        allTrainers: "Alle trainer",
        myTrainers: 'Meine trainer',
        subscribe: 'Abonnieren',
        unsubscribe: 'Abbestellen',

    },
    ru: {
        password:"Пароль",
        password_confirmation: "Подтвердите пароль",
        login:"Вход",
        submit:"Подтвердить",
        register:"Регистрация",
        name:"Имя",
        confirmPolicy: 'Я согласен с условиями использования сервиса',
        resetPassword: 'Сброс пароля',
        diary: 'Дневник',
        trainers: 'Тренера',
        food: 'Питание',
        activity: 'Активность',
        progress: 'Прогресс',
        personal: 'Персональная',
        diary_food: 'Дневник питания',
        diary_activity: 'Дневник активности',
        selectedDate: 'Выбранная дата:',
        foodName: 'Название продукта',
        date: 'Дата',
        time: 'Время',
        kcal: 'Ккал',
        weightPortion: 'Вес порции',
        close: 'Закрыть',
        save: 'Сохранить',
        protein: 'Белки (г)',
        fat: 'Жиры (г)',
        carbohydrates: 'Углеводы (г)',
        water: 'Вода (г)',
        activityName: 'Название активности',
        numberApproaches: 'Количество подходов*',
        timeOneExercise: 'Время на выполнение подхода*',
        numberOfRepetitions: 'Количество повторений',
        restNextToApproach: 'Время отдыха до след. подхода',
        burdenWeight: 'Вес отягощения',
        searchNickName: 'Поиск по псевдониму',
        allTrainers: 'Все тренера',
        myTrainers: 'Мои тренера',
        subscribe: 'Подписаться',
        unsubscribe: 'Отписаться',

    }
});

export { Lang }