import LocalizedStrings from 'react-native-localization';

const Lang = new LocalizedStrings({
    en:{
        password:"Password",
        password_confirmation: "Confirm password",
        login:"Login",
        submit:"Submit",
        register: "Register",
        name: "Name",
        confirmPolicy: 'I agree to the terms of service',
        resetPassword: 'Password Reset',
        diary: 'Diary',
        trainers: 'Trainers',
        food: 'Food',
        activity: 'Activity',
        progress: 'Progress',
        personal: 'Personal',
        diary_food: 'Food Diary',
        diary_activity: 'Activity Diary',
    },
    de: {
        password:"Passwort",
        password_confirmation: "Passwort bestätigen",
        login:"Anmeldung",
        submit:"Einreichen",
        register: "Anmelden",
        name: "Name",
        confirmPolicy: 'Ich stimme den Nutzungsbedingungen zu',
        resetPassword: 'Passwort zurücksetzen',
        diary: 'Tagebuch',
        trainers: "Trainer",
        food: 'Essen',
        activity: 'Aktivität',
        progress: 'Fortschritt',
        personal: 'Persönlich',
        diary_food: 'Ernährungstagebuch',
        diary_activity: 'Aktivitätstagebuch',

    },
    ru: {
        password:"Пароль",
        password_confirmation: "Подтвердите пароль",
        login:"Вход",
        submit:"Подтвердить",
        register:"Регистрация",
        name:"Имя",
        confirmPolicy: 'Я согласен с условиями использования сервиса',
        resetPassword: 'Сброс пароля',
        diary: 'Дневник',
        trainers: 'Тренера',
        food: 'Питание',
        activity: 'Активность',
        progress: 'Прогресс',
        personal: 'Персональная',
        diary_food: 'Дневник питания',
        diary_activity: 'Дневник активности',
    }
});

export { Lang }